### ISSUE TITLE
How to use another engine with MzingaViewer?

### ISSUE THREAD

**Issue by edre** [jonthysell/Mzinga#103]
I found a menu to tweak engine options, but not a place to choose a different engine.

**Comment by jonthysell** [comment]
Under the Viewer Config, there's an Engine option to choose engine for the Viewer.

Internal is just Mzinga's engine, External let's you put in the command-line to execute another engine.

**Comment by edre** [comment]
I'm using the linux viewer, and I don't see an External option.

**Comment by jonthysell** [comment]
It's under Viewer Options, under the Engine tab.

![image](https://user-images.githubusercontent.com/10852185/109588601-e25bb280-7abd-11eb-876e-dd879b40ad53.png)

Select "Use UHP Engine" and put in the command line to start the engine. Then restart the viewer.

What engine are you trying to use?

**Comment by edre** [comment]
Aaaah, I was only looking under the Engine menu. I found it in the viewer tab. Now I can start implementing a UHP server for my engine.
