### ISSUE TITLE
AI Strength

### ISSUE THREAD

**Issue by tmountain** [jonthysell/Mzinga#110]
Hi,

Firstly, this project is awesome. It's great to see an open source initiative focused on such a wonderful game. That said, I'm a novice hive player (< 100 hours invested), and I beat the AI pretty easily at default settings. Is this to be expected? It'd be great to have some UI elements to tune to a standard difficulty (easy / medium / hard).

Secondly, as a minor complaint, the board adjusts its coordinate position every time a new piece is placed. I believe this is done in the interest of keeping it centered. That said, it's a disorienting behavior and requires you to visually adjust to the piece positions every time. 

My suggestion would be to leave the piece as they are and allow the player to move the entire board via the mouse if reorientation is needed. Anyway, thanks for the cool project. I'll be keeping an eye on it.

**Comment by jonthysell** [comment]
FYI @tmountain, user-controlled scrolling and zoom of the board was added in v0.11.5.

**Comment by tmountain** [comment]
@jonthysell Awesome, I'll take a look. Thanks for the update!
